### ISSUE TITLE
New version upload

### ISSUE THREAD

**Issue by sarthakpati** [PingjunChen/pyslide#8]
Hi,

Could you please upload 0.4.3 to pip? I need this version to finish the [conda recipe](https://github.com/conda-forge/staged-recipes/pull/14475) of this package. 😄 

Cheers,
Sarthak

**Comment by PingjunChen** [comment]
work on it now.

**Comment by PingjunChen** [comment]
Updated to 0.4.3 in pypi. Seems setuptools>=50.0.0 is not compatible with openslide-python==1.1.1. Please help double check.  setuptools==45 works on my side.

**Comment by sarthakpati** [comment]
Maybe we could update openslide-python to 1.1.2?

**Comment by PingjunChen** [comment]
works for me. Please help with that!

**Comment by sarthakpati** [comment]
> works for me. Please help with that!

Added: https://github.com/PingjunChen/pyslide/pull/9

**Comment by PingjunChen** [comment]
Update the package version requirements already, and version 0.4.4 is pushed to https://pypi.org/. thanks for the help on conda.

**Comment by sarthakpati** [comment]
BTW, is openslide-python required or is just openslide enough?

**Comment by PingjunChen** [comment]
@sarthakpati  Not sure I understand your question right or not. Based on my knowledge, openside-python is required. OpenSlide is the C library that underlying openside-python.

**Comment by sarthakpati** [comment]
Right, but "openslide-python" is not present in conda, but "openslide" is (which contains the python wrappers, as well). Anyway, I am checking how this can be done in a nice manner.

**Comment by sarthakpati** [comment]
Let me know when the new version is up. Thanks for your patience while I work this out!

**Comment by PingjunChen** [comment]
version 0.4.5 uploaded to pypi already. Would add more functionalities to this repo when not busy. Thanks for your efforts!
